### ISSUE TITLE
在文章的作者信息部分添加复制链接按钮

### ISSUE THREAD

**Issue by Stars-harbor** [everfu/hexo-theme-solitude#303]
### 功能简介

在点击按钮时可快捷将文章链接复制至剪贴板，方便分享文章链接

### 问题描述

手机端网站开启pwa且安装到桌面后，因为浏览器的一些限制可能无法正确显示右键菜单，且快捷分享功能也没有复制链接的按钮。希望在文章末尾、显示作者信息的位置添加一个按钮用来快捷复制文章链接

### 实现效果

便于文章链接的快捷复制

### 其他内容

![Screenshot_20240614_113450](https://github.com/everfu/hexo-theme-solitude/assets/112921458/8657400f-ae09-4110-a944-0ff5535ffdda)
样式参考

**Comment by everfu** [comment]
这个效果是否可行？
<img width="516" alt="image" src="https://github.com/everfu/hexo-theme-solitude/assets/74389842/c7b5b6ab-39c5-46b7-93ed-8500551bd507">

**Comment by Stars-harbor** [comment]
似乎也是可以的

**Comment by everfu** [comment]
这样子怎么样
<img width="580" alt="image" src="https://github.com/everfu/hexo-theme-solitude/assets/74389842/7537e567-cde3-43c7-8346-b5a04ca4519f">

**Comment by Stars-harbor** [comment]
如果看外观的一致性，似乎方形＋圆角更美观统一一些（个人意见）

**Comment by everfu** [comment]
好，已经提交到 dev 了，可以去帮我测试一下
a1291f11960250ad63047c177cbb8bbfad3a68a1

**Comment by everfu** [comment]
```yaml
  share:
    enable: false
    list:
    #  - qq
    #  - weibo
    #  - twitter
    #  - facebook
    #  - telegram
    #  - whatsapp
    #  - linkedin
    #  - link
    #  - qrcode
```
