### ISSUE TITLE
[Bug]: 侧边栏二维码组件不显示

### ISSUE THREAD

**Issue by VXenomac** [everfu/hexo-theme-solitude#396]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

```
# --------------------------- start ---------------------------
  # Sidebar QR code component
  # 侧边栏二维码组件
  flip:
    favicon: https://p.zhheo.com/i28Q2z23790881691546797700.png!cover # url (favicon)
    face: https://p.zhheo.com/Y87vtG22690881691546426143.png!cover # url (QR code)
    backface: https://p.zhheo.com/kqz0Lk25390681718271533221.png!cover # url (QR code)
    backcolor: "var(--efu-blue)" # Background color
  # --------------------------- end ---------------------------
```
设置了如上的侧边栏二维码组件，但是没有显示

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/396">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/396/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/396/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
仔细阅读文档，
```yaml
aside:
  # Values: about (info card), newestPost (latest article), allInfo (website information), flip (official account QR code), newest_comment (latest comment)
  # 值: about(信息卡), newestPost(最新文章), allInfo(网站信息), flip(官方账号二维码), newest_comment(最新评论)、ads(广告)

  # Sticky: Fixed position / noSticky: Not fixed position
  # Sticky: 固定位置 / noSticky: 不固定位置
  home: # on the homepage
    noSticky: "about,newest_comment"
    Sticky: "allInfo"
  post: # on the article page
    noSticky: "about"
    Sticky: "newestPost"
  page: # on the page
    noSticky: "about"
    Sticky: "newestPost,allInfo"
```
在需要的页面后面添加相应的
