### ISSUE TITLE
[Bug]: 代码块显示错误  and  文章末版权显示问题

### ISSUE THREAD

**Issue by zephyr2233** [everfu/hexo-theme-solitude#418]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

1. 代码块渲染问题

不知道为什么，我文章的代码块在文章里面显示都会再加上一层行内代码的渲染效果

主题config配置：

```
# Highlight
# 代码块高亮
highlight:
  enable: true
  # Display the fold button when the number of words exceeds
  # 当超过多少字时显示折叠按钮
  limit: 200
  # Whether to enable the copy button
  # 是否启用复制按钮
  copy: true
  # Whether to expand by default
  # 是否默认展开
  expand: true
  # default: default / mac : apple terminal
  # default: 默认 / mac : 苹果终端
  theme: mac
  # default / solidity / dracula
  color: default
```

博客内容：

![图片](https://github.com/user-attachments/assets/deb0b2ed-8ac1-43a4-9254-523d9f655c88)

显示样式：
![图片](https://github.com/user-attachments/assets/7ba06bf4-f1e5-4f3b-9548-c2f9f9fcc9fa)

--------------

2. 文章末尾版权信息问题

文章末尾不是显示主题配置之中我填写的内容，而是全部使用站点icon，标题和副标题内容

主题config配置：
```
    # 版权
    copyright:
      enable: true
      author: zephyr
      discription: 随缘分享~
      url: /about/ # Author link
        # Default use site.icon
        # 默认使用 site.icon
      img: https://s2.loli.net/2024/10/28/7VaIQjUGHkuCq85.webp
      # License
      # 许可证
      license: CC BY-NC-SA 4.01
      # License link
      # 许可证链接
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
```

显示：

![图片](https://github.com/user-attachments/assets/ecbcc188-4d25-4672-870e-df27bcfae488)

这里使用的是站点的icon，标题和副标题，不是版权配置之中填写的author和discription

终端渲染都正常，没有报错。

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/418">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/418/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/418/pledge.svg">
</picture>
</a>
