### ISSUE TITLE
[Feature]: pjax exclude

### ISSUE THREAD

**Issue by manman-dong** [everfu/hexo-theme-solitude#420]
### 功能简介

博客部分页面不使用pjax

### 问题描述

能否像butterfly主题类似，在主题配置config配置部分内容不使用pjax加载

```
pjax:
  enable: true
  # Exclude the specified pages from pjax, such as '/music/'
  exclude:
    # - /xxxxxx/
    ```

### 实现效果

```
pjax:
  enable: true
  # Exclude the specified pages from pjax, such as '/music/'
  exclude:
    # - /xxxxxx/
    ```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/420">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/420/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/420/pledge.svg">
</picture>
</a>
