### ISSUE TITLE
[Feature]: 友链页友链轮播增加开关

### ISSUE THREAD

**Issue by Linux-qitong** [everfu/hexo-theme-solitude#448]
### 功能简介

对于友链较少的网站友好

### 问题描述

没有任何问题

### 实现效果

没有友链轮播，可以自由开关

**Comment by Qiu-Quanzhi** [comment]
推荐通过注入css的方式来禁用滚动动画。
新建样式表，然后添加进inject head项中，其他滚动视图同理。
```css
.flink /*swiper的父类*/ .tags-group-wrapper{
    animation: none !important;
}
```
