### ISSUE TITLE
分享图标不显示，关闭分享后依旧占用空间。

### ISSUE THREAD

**Issue by Oilan94** [everfu/hexo-theme-solitude#470]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

配置文件开启share后，网页不显示图标，只有空白。关闭后依旧占用空间。
![Screenshot_20250104_204255_Lemur Browser](https://github.com/user-attachments/assets/69f43020-d0f1-4b75-934c-9754496ed6b3)
![Screenshot_20250104_203203_Chrome](https://github.com/user-attachments/assets/e680af22-56f7-44d4-a7b7-e926679013ce)
![Screenshot_20250104_203449_GitHub](https://github.com/user-attachments/assets/d6be893c-69a8-482c-9682-2995fc3ced5a)

**Comment by Qiu-Quanzhi** [comment]
未能复现，这边关闭后不会渲染，在github dev分支下测试

**Comment by Oilan94** [comment]
> 未能复现，这边关闭后不会渲染，在github dev分支下测试

开启后能正常显示吗？还是说正常显示需要配置别的选项。

**Comment by Qiu-Quanzhi** [comment]
> > 未能复现，这边关闭后不会渲染，在github dev分支下测试
> 
> 开启后能正常显示吗？还是说正常显示需要配置别的选项。

似乎开关都正常……起码应该会有一个订阅按钮才对

**Comment by everfu** [comment]
```yaml
  share:
    enable: true
    list:
      - qq
      - weibo
      - twitter
      - facebook
      - telegram
      - whatsapp
      - linkedin
      - link
      - qrcode
```
合理
