### ISSUE TITLE
[Bug]: 侧边栏tag控制失效

### ISSUE THREAD

**Issue by it985** [everfu/hexo-theme-solitude#491]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

# 侧边栏tag控制失效
## 配置
_config.solitude.yml
```yml
# 侧边栏
aside:
....
  # Tags
  # 标签
  tags:
    enable: true
    limit: 20 # Number of tags displayed
    # Highlighted tags
    highlight_list:
      # - Hexo
```
## 线上截图
https://blog.study996.cn

![image](https://github.com/user-attachments/assets/f7a1091d-80bb-40d3-a640-1ad2c7e5a93b)

## 本地截图
![image](https://github.com/user-attachments/assets/2a976b10-8979-40d4-a8d6-c243bb4f6a63)

# 侧边栏tag明显超过20个，设置失效
