### ISSUE TITLE
[Feature]: 在首页导航栏右侧添加显示模式切换按钮

### ISSUE THREAD

**Issue by Mengqyzh** [everfu/hexo-theme-solitude#568]
### 功能简介

在首页导航栏右侧添加显示模式切换按钮

### 问题描述

目前网站的显示模式切换按钮在右键菜单或者右下角悬停导航栏，不是很直观，希望在在首页导航栏右侧菜单添加显示模式切换按钮。

### 实现效果

![Image](https://github.com/user-attachments/assets/58667aef-2513-400f-846c-c489fb7da02b)

### 你想到的可行的替代方案

在right.pug搜索图标后面添加显示模式按钮开关
if theme.display_mode.mode 
        .nav-button
            a.site-page(onclick="sco.switchDarkMode()", title=_p('rightside.hide.mode'))
                i.fas.fa-circle-half-stroke
_config.yml中添加控制
display_mode:
        mode: true

**Comment by everfu** [comment]
```yml
  # Right button
  # 右侧按钮
  right:
    random: true # 随机文章跳转 / random post button
    console: true # 控制台 / console
    custom:
      - name: 切换主题
        url: javascript:sco.switchDarkMode()
        icon: fas fa-adjust
        id: theme_button
```
